modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://github.com/Example/Example" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc"
    mandatory=true
    versionRange="${tfc_version_range}"
    ordering="AFTER" # so our mod loads data after theirs
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="alexsmobs"
    mandatory=true
    versionRange="${alexsmobs_version_range}"
    ordering="AFTER" # so our mod loads data after theirs
    side="BOTH"